### ISSUE TITLE
Can QuASI be used on ome.tiff images with multiple channels which have already been stitched?

### ISSUE THREAD

**Issue by WilmaOlsson** [MarkZaidi/QuPath-Image-Alignment#4]
Thank you for a great tool.
In your video tutorial the input images are named according to their staining. I want to register and overlay immunofluorescence ome.tiff images of the same tissue, but with different staining created using a cyclic staining protocol. Each image has 4 channels with one stain/channel, one being the nuclear stain (which is applied in every cycle) which is what I want to use as reference for alignment. Can this be done and in that case what should I name the files that contain multiple stains/channels? Would a better solution be to generate tiff-files from my scanner, with one tiff-image per channel, for every cycle?

I believe I should use the line "// Use a single channel from each image for alignment (set to channel number to use). Set to 0 to use all channels." for this, but when I change its value from 0 the script can no longer run. 
Thank you for your help!

**Comment by MarkZaidi** [comment]
>Can this be done and in that case what should I name the files that contain multiple stains/channels?

Yes, under the `experimental features` section of `Calculate-Transforms.groovy`, set `use_single_channel` to the channel that the nuclear stain is on. For example, if DAPI is the 4th channel for both of your images, set `use_single_channel=4`. This assumes that the nuclear counterstain channel is in the same order across images. If it isn't, you'll need to reorder channels prior to using QuASI (this can be done using NumPy in Python, or reordering channels in MATLAB as an example) . I don't think I covered this in the video, as it was implemented after I recorded it.

> Would a better solution be to generate tiff-files from my scanner, with one tiff-image per channel, for every cycle?

No, as the channels generated from any scanner are already aligned internally to one another. If we start computing the transformation for each channel individually, we'll lose what was an already near-perfect alignment between individual channels of a single image. All channels of an image should be kept as one file (any format that QuPath can load is sufficient). As long as the channel position of the DNA counterstain remains constant across cycles, you can use the `use_single_channel` approach as previously described.

> I believe I should use the line "// Use a single channel from each image for alignment (set to channel number to use). Set to 0 to use all channels." for this, but when I change its value from 0 the script can no longer run.

Ah, then in that case, it is a bug. But yes, you are absolutely correct, that's what I would have done. Would you be willing to share the error message, and the images for which this occurred? I can provide a private Google Drive folder for you to upload them.

> Thank you for your help!

Thanks for using QuASI 😄

**Comment by WilmaOlsson** [comment]
Hi!
Thank you for your quick response.
I am pretty sure that the nuclear stain channel has the same number across
the images. At least when I align images ”using all channels”, the
resulting images present the channels from im1 and im2 in the same order in
Qupath. Is there another way to check that the stains are in the correct
order across images? I have yet not generated the images I actually need to
align but I am currently testing the registration solution on images
derived in the same way and in the same format. I have also aligned an
image to itself, just to try out the code, but even then the "Use a single
channel" did not work, and since the images were duplicates the channels
numbers should definitely match.

 When running transformation "on all channels" both scripts can be run and
registration occurs, however some warnings appear:
Transform script:
WARN: BioFormatsImageServer.readBufferedImage(RegionRequest) is deprecated
- please use BioFormatsImageServer.readRegion(RegionRequest) instead

Align script:
WARN: Arbitrary transform cannot be decomposed! I will use the default
pixel calibration.
INFO: Saving project Project: Sttiching_test_TMA_Qupath-project...

When trying to calculate the transformation using 1 channel, a long error
message appears that I have attached in a word document. This is for trying
to align two TMA, ome.tiff files (the same image) which I have renamed with
the extension .tiff. When running on all channels, they are aligned but
this will not be enough when aligning images that are in fact stained with
different stains.

I would gladly share some representative images, let me just talk to my
supervisor to make sure that it is fine and try to find suitable test
images! I will get back to you during the day.

Again, thanks a lot for your help! :)

Best Regards,
Wilma




ons 8 mars 2023 kl. 21:43 skrev MarkZaidi ***@***.***>:

**Comment by WilmaOlsson** [comment]
Hi again!
I have found some test images that I can send :)
Just send me a link to the docx-file.

Best Regards,
Wilma

Den tors 9 mars 2023 kl 09:12 skrev Wilma Olsson ***@***.***>:

**Comment by MarkZaidi** [comment]
> Is there another way to check that the stains are in the correct order across images?

If you load the images into QuPath, it'll say which channel is which in the `Brightness and Contrast` window, followed by a bracket containing the channel number for each channel (e.g. C4)

> a long error message appears that I have attached in a word document

I don't think Github supports sharing .docx files, as I don't see any attached document. I'll send you a link to a Google Drive folder for you to upload both the long error message and test images too.

Can you provide me with a gmail email address that I can privately share the folder with you?

**Comment by WilmaOlsson** [comment]
Hi!
Thank you.
My email-address is ***@***.***


Den fre 10 mars 2023 kl 16:40 skrev MarkZaidi ***@***.***>:

**Comment by MarkZaidi** [comment]
> My email-address is ***@***.***

Hmm, for whatever reason, it seems like your email is being masked (probably some security feature on github). Can you send me a message on the image.sc forums (https://forum.image.sc/u/mark_zaidi/summary), and I can send you a link to the google drive folder
